pipeline {
    agent {
        label "master"
    }
    tools{
     maven 'maven3.3.9'   
    }

    stages {
        stage('preparation') {
            git '
           
        }
        
        stage('Compile') {
            steps {
            
              sh 'mvn clean compile'
                echo 'Compiling.'
                }
           
        }
       stage('Testing') {
            steps {
            
              sh 'mvn test'
                echo 'Testing..'
                }
           
        }
       stage('Deploy') {
            steps {
           
              sh 'mvn deploy'
                echo 'Building..'
                }
          
        }
    }
}
