pipeline {
    agent {
        label "master"
    }
    tools{
     maven 'maven3.3.9'   
    }

    stages {
           
        stage('Compile') {
            
            steps {
                git'git@github.com:dhanu629/wardeploy.git'
            
              sh 'mvn -f project1/pom.xml clean compile'
                echo 'Compiling.'
                }
           
        }
       stage('Testing') {
            steps {
            
              sh 'mvn test'
                echo 'Testing..'
                }
           
        }
       stage('Deploy') {
            steps {
           
              sh 'mvn deploy'
                echo 'Building..'
                }
          
        }
    }
}
